title: Rachael Friedman
logo: "images\rachael_picture.PNG"
description: >
  I am a data scientist with expertise in data analytics and visualization
  consulting that is passionate about helping companies unpack and leverage
  data to make strategic decisions. My detail-oriented and collaborative
  approach to solving problems enables me to be a strong team player and
  dedicated partner to my stakeholders.
  <br><br>

  <a href="https://www.linkedin.com/in/rachael-friedman/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
